import { ToolDefinition } from '../../shared/models/tool-definition.model';

export const TOOL_DEFINITIONS: readonly ToolDefinition[] = [
  {
    id: 'text-inspector',
    title: 'Text Inspector',
    description: 'Character, word, line, and byte metrics for any text.',
    category: 'text',
    keywords: ['text', 'inspector', 'count', 'characters', 'words', 'lines', 'bytes', 'metrics'],
    route: '/tools/text-inspector',
    load: () => import('../../tools/text-inspector/text-inspector').then((m) => m.TextInspector),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'base64',
    title: 'Base64 Encoder / Decoder',
    description: 'UTF-8-safe text-to-Base64 and Base64-to-text conversion.',
    category: 'encoding',
    keywords: ['base64', 'encode', 'decode', 'encoding', 'utf-8'],
    route: '/tools/base64',
    load: () => import('../../tools/base64/base64').then((m) => m.Base64Tool),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'unix-timestamp',
    title: 'Unix Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates.',
    category: 'date-time',
    keywords: ['unix', 'timestamp', 'epoch', 'date', 'time', 'utc', 'convert'],
    route: '/tools/unix-timestamp',
    load: () => import('../../tools/unix-timestamp/unix-timestamp').then((m) => m.UnixTimestamp),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'jwt',
    title: 'JWT Debugger',
    description: 'Decode a JWT header and payload — does not verify signatures.',
    category: 'security',
    keywords: ['jwt', 'json web token', 'decode', 'auth', 'token', 'claims'],
    route: '/tools/jwt',
    load: () => import('../../tools/jwt/jwt').then((m) => m.Jwt),
    status: 'stable',
    persistence: { input: 'none', preferences: 'none' },
  },
  {
    id: 'hash',
    title: 'Hash Generator',
    description: 'MD5, SHA-1, SHA-256, SHA-384, and SHA-512 digests for text.',
    category: 'security',
    keywords: ['hash', 'checksum', 'md5', 'sha1', 'sha256', 'sha512', 'digest'],
    route: '/tools/hash',
    load: () => import('../../tools/hash/hash').then((m) => m.Hash),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'markdown',
    title: 'Markdown Preview',
    description: 'Live side-by-side Markdown editor and sanitized HTML preview.',
    category: 'documents',
    keywords: ['markdown', 'md', 'preview', 'render', 'documents'],
    route: '/tools/markdown',
    load: () => import('../../tools/markdown/markdown').then((m) => m.Markdown),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'regex',
    title: 'Regex Tester',
    description: 'Test a regular expression against text with match and capture-group details.',
    category: 'developer',
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test', 'capture groups'],
    route: '/tools/regex',
    load: () => import('../../tools/regex/regex').then((m) => m.Regex),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'diff',
    title: 'Text Diff',
    description: 'Line-oriented diff between two blocks of text.',
    category: 'text',
    keywords: ['diff', 'compare', 'text', 'changes', 'delta'],
    route: '/tools/diff',
    load: () => import('../../tools/diff/diff').then((m) => m.Diff),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'json',
    title: 'JSON Formatter',
    description: 'Validate, format, and minify JSON, with an editable tree view, structural compare, and malformed-JSON repair.',
    category: 'data',
    keywords: ['json', 'format', 'validate', 'pretty', 'minify', 'tree', 'edit', 'compare', 'diff', 'repair'],
    route: '/tools/json',
    load: () => import('../../tools/json/json').then((m) => m.Json),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'uuid',
    title: 'UUID Generator / Inspector',
    description: 'Generate v1/v4/v5/v7 UUIDs (with namespace support), inspect an existing UUID, and bulk-export the generated list.',
    category: 'developer',
    keywords: ['uuid', 'guid', 'generate', 'inspect', 'identifier', 'rfc 4122', 'namespace', 'v1', 'v5', 'v7'],
    route: '/tools/uuid',
    load: () => import('../../tools/uuid/uuid').then((m) => m.Uuid),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'url-encode',
    title: 'URL Encoder / Decoder',
    description: 'Percent-encode or decode text as a URL component or a full URI.',
    category: 'encoding',
    keywords: ['url', 'uri', 'encode', 'decode', 'percent-encoding', 'escape', 'unescape'],
    route: '/tools/url-encode',
    load: () => import('../../tools/url-encode/url-encode').then((m) => m.UrlEncode),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'query-string',
    title: 'Query String Parser / Builder',
    description: 'Parse a query string or URL into key/value pairs, or build one from scratch.',
    category: 'web',
    keywords: ['query string', 'query params', 'url', 'parse', 'build', 'search params'],
    route: '/tools/query-string',
    load: () => import('../../tools/query-string/query-string').then((m) => m.QueryString),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'case-converter',
    title: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, kebab-case, Title Case, and more.',
    category: 'text',
    keywords: ['case', 'convert', 'camelcase', 'snake_case', 'kebab-case', 'title case', 'pascalcase'],
    route: '/tools/case-converter',
    load: () => import('../../tools/case-converter/case-converter').then((m) => m.CaseConverter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'whitespace-cleaner',
    title: 'Whitespace Cleaner / Normalizer',
    description: 'Trim, collapse, and normalize whitespace, line endings, and invisible characters.',
    category: 'text',
    keywords: ['whitespace', 'trim', 'clean', 'normalize', 'line endings', 'tabs', 'spaces', 'invisible'],
    route: '/tools/whitespace-cleaner',
    load: () => import('../../tools/whitespace-cleaner/whitespace-cleaner').then((m) => m.WhitespaceCleaner),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'slug-generator',
    title: 'Slug Generator',
    description: 'Turn a title into a URL-friendly slug, with transliteration and length control.',
    category: 'text',
    keywords: ['slug', 'url', 'permalink', 'seo', 'transliterate', 'hyphenate'],
    route: '/tools/slug-generator',
    load: () => import('../../tools/slug-generator/slug-generator').then((m) => m.SlugGenerator),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'html-entities',
    title: 'HTML Entity Encoder / Decoder',
    description: 'Encode text as HTML entities, or decode named and numeric entities back to text.',
    category: 'encoding',
    keywords: ['html', 'entity', 'entities', 'encode', 'decode', 'escape', 'unescape', 'amp', 'nbsp'],
    route: '/tools/html-entities',
    load: () => import('../../tools/html-entities/html-entities').then((m) => m.HtmlEntities),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'color-converter',
    title: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL, HSV, CMYK, and named CSS colors.',
    category: 'encoding',
    keywords: ['color', 'colour', 'hex', 'rgb', 'hsl', 'hsv', 'cmyk', 'convert', 'css color'],
    route: '/tools/color-converter',
    load: () => import('../../tools/color-converter/color-converter').then((m) => m.ColorConverter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'number-base',
    title: 'Number Base Converter',
    description: 'Convert whole numbers between binary, octal, decimal, hex, or any base 2–36.',
    category: 'encoding',
    keywords: ['number', 'base', 'binary', 'octal', 'decimal', 'hex', 'hexadecimal', 'radix', 'convert'],
    route: '/tools/number-base',
    load: () => import('../../tools/number-base/number-base').then((m) => m.NumberBase),
    status: 'stable',
    persistence: { input: 'local', preferences: 'none' },
  },
  {
    id: 'yaml-json',
    title: 'YAML ↔ JSON Converter',
    description: 'Convert between YAML and JSON, in either direction.',
    category: 'data',
    keywords: ['yaml', 'json', 'convert', 'yml', 'data'],
    route: '/tools/yaml-json',
    load: () => import('../../tools/yaml-json/yaml-json').then((m) => m.YamlJson),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'xml-formatter',
    title: 'XML Formatter',
    description: 'Validate, format, and minify XML.',
    category: 'data',
    keywords: ['xml', 'format', 'validate', 'pretty', 'minify'],
    route: '/tools/xml-formatter',
    load: () => import('../../tools/xml-formatter/xml-formatter').then((m) => m.XmlFormatter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'csv-viewer',
    title: 'CSV Viewer / Converter',
    description: 'View CSV as a table, and convert between CSV and JSON.',
    category: 'data',
    keywords: ['csv', 'table', 'convert', 'json', 'tsv', 'spreadsheet'],
    route: '/tools/csv-viewer',
    load: () => import('../../tools/csv-viewer/csv-viewer').then((m) => m.CsvViewer),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'json-query',
    title: 'JSONPath / JMESPath Tester',
    description: 'Query JSON with a JSONPath or JMESPath expression.',
    category: 'data',
    keywords: ['jsonpath', 'jmespath', 'query', 'json', 'filter', 'search'],
    route: '/tools/json-query',
    load: () => import('../../tools/json-query/json-query').then((m) => m.JsonQuery),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'http-status',
    title: 'HTTP Status Code Reference',
    description: 'Searchable reference of every IANA-registered HTTP status code.',
    category: 'web',
    keywords: ['http', 'status', 'code', 'response', 'reference', '404', '500'],
    route: '/tools/http-status',
    load: () => import('../../tools/http-status/http-status').then((m) => m.HttpStatus),
    status: 'stable',
    persistence: { input: 'local', preferences: 'none' },
  },
  {
    id: 'http-header-inspector',
    title: 'HTTP Header Inspector / Builder',
    description: 'Inspect pasted HTTP headers as key/value pairs, or build a header set from scratch.',
    category: 'web',
    keywords: ['http', 'header', 'headers', 'inspect', 'build', 'request', 'response'],
    route: '/tools/http-header-inspector',
    load: () =>
      import('../../tools/http-header-inspector/http-header-inspector').then((m) => m.HttpHeaderInspector),
    status: 'stable',
    persistence: { input: 'none', preferences: 'none' },
  },
  {
    id: 'curl-converter',
    title: 'cURL Command Inspector / Converter',
    description: 'Parse a cURL command into its parts, build one interactively, and export it as code.',
    category: 'web',
    keywords: ['curl', 'http', 'request', 'convert', 'fetch', 'code export'],
    route: '/tools/curl-converter',
    load: () => import('../../tools/curl-converter/curl-converter').then((m) => m.CurlConverter),
    status: 'stable',
    persistence: { input: 'none', preferences: 'local' },
  },
  {
    id: 'cron',
    title: 'Cron Expression Parser',
    shortTitle: 'Cron Parser',
    description: 'Parse a cron expression into a human-readable schedule and preview its next run times.',
    category: 'date-time',
    keywords: ['cron', 'crontab', 'schedule', 'next run', 'expression'],
    route: '/tools/cron',
    load: () => import('../../tools/cron/cron').then((m) => m.Cron),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'user-agent',
    title: 'User-Agent Parser',
    description: 'Break a User-Agent string down into browser, engine, OS, and device details.',
    category: 'web',
    keywords: ['user agent', 'ua', 'browser', 'device', 'os', 'parse'],
    route: '/tools/user-agent',
    load: () => import('../../tools/user-agent/user-agent').then((m) => m.UserAgent),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'mime-types',
    title: 'MIME Type Reference',
    description: 'Searchable reference of common IANA-registered MIME types with file-extension lookups.',
    category: 'web',
    keywords: ['mime', 'media type', 'content-type', 'file extension', 'reference'],
    route: '/tools/mime-types',
    load: () => import('../../tools/mime-types/mime-types').then((m) => m.MimeTypes),
    status: 'stable',
    persistence: { input: 'local', preferences: 'local' },
  },
  {
    id: 'semver-comparator',
    title: 'Semantic Version Comparator',
    description: 'Compare, sort, and range-check versions against the Semantic Versioning spec.',
    category: 'developer',
    keywords: ['semver', 'semantic version', 'compare', 'sort', 'range', 'version'],
    route: '/tools/semver-comparator',
    load: () => import('../../tools/semver-comparator/semver-comparator').then((m) => m.SemverComparator),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'glob-tester',
    title: 'Glob Pattern Tester',
    description: 'Test a glob pattern against a list of sample paths.',
    category: 'developer',
    keywords: ['glob', 'pattern', 'match', 'wildcard', 'test', 'paths', 'gitignore'],
    route: '/tools/glob-tester',
    load: () => import('../../tools/glob-tester/glob-tester').then((m) => m.GlobTester),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'url-inspector',
    title: 'URL / URI Inspector',
    description: 'Break a URL down into scheme, host, path, query, and fragment — and edit any part.',
    category: 'web',
    keywords: ['url', 'uri', 'inspector', 'parse', 'scheme', 'host', 'query', 'fragment'],
    route: '/tools/url-inspector',
    load: () => import('../../tools/url-inspector/url-inspector').then((m) => m.UrlInspector),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'timezone-converter',
    title: 'Date / Timezone Converter',
    description: 'Convert a moment in time across a chosen set of IANA timezones.',
    category: 'date-time',
    keywords: ['timezone', 'time zone', 'date', 'convert', 'world clock', 'iana', 'dst', 'utc offset'],
    route: '/tools/timezone-converter',
    load: () => import('../../tools/timezone-converter/timezone-converter').then((m) => m.TimezoneConverter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'date-calculator',
    title: 'Date Calculator',
    description: 'Add/subtract calendar or business days from a date, and count days/weekdays/business-days between two dates.',
    category: 'date-time',
    keywords: ['date', 'calculator', 'business days', 'weekdays', 'holidays', 'add days', 'days between'],
    route: '/tools/date-calculator',
    load: () => import('../../tools/date-calculator/date-calculator').then((m) => m.DateCalculator),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'recurrence-rule',
    title: 'Recurrence Rule Calculator',
    description: 'Expand an iCal-style RRULE recurrence into a list of occurrence dates — event recurrence, distinct from cron trigger schedules.',
    category: 'date-time',
    keywords: ['rrule', 'recurrence', 'recurring', 'ical', 'calendar', 'schedule', 'occurrence'],
    route: '/tools/recurrence-rule',
    load: () => import('../../tools/recurrence-rule/recurrence-rule').then((m) => m.RecurrenceRule),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'duration-formatter',
    title: 'Duration Parser / Formatter',
    description: 'Parse a human or ISO 8601 duration and see it in every representation at once.',
    category: 'date-time',
    keywords: ['duration', 'parse', 'format', 'iso 8601', 'milliseconds', 'human readable'],
    route: '/tools/duration-formatter',
    load: () => import('../../tools/duration-formatter/duration-formatter').then((m) => m.DurationFormatter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'random-data-generator',
    title: 'Random Data Generator',
    description: 'Generate realistic fake data — names, addresses, internet, finance, and more — as a table, CSV, or JSON.',
    category: 'developer',
    keywords: ['random', 'fake', 'faker', 'mock', 'data', 'generate', 'test data', 'sample data'],
    route: '/tools/random-data-generator',
    load: () => import('../../tools/random-data-generator/random-data-generator').then((m) => m.RandomDataGenerator),
    status: 'stable',
    persistence: { input: 'local', preferences: 'local' },
  },
  {
    id: 'file-hash',
    title: 'File Hash Generator',
    shortTitle: 'File Hash',
    description: 'MD5, SHA-1, SHA-256, SHA-384, and SHA-512 digests for a local file.',
    category: 'security',
    keywords: ['hash', 'file', 'checksum', 'md5', 'sha1', 'sha256', 'sha512', 'digest', 'integrity', 'verify'],
    route: '/tools/file-hash',
    load: () => import('../../tools/file-hash/file-hash').then((m) => m.FileHash),
    status: 'stable',
    persistence: { input: 'none', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'file-base64',
    title: 'File Base64 Converter',
    shortTitle: 'File Base64',
    description: 'Convert a local file to Base64 text, or a Base64 string back into a downloadable file, with MIME sniffing and an image preview.',
    category: 'encoding',
    keywords: ['base64', 'file', 'encode', 'decode', 'download', 'binary', 'convert', 'attachment', 'mime', 'image preview'],
    route: '/tools/file-base64',
    load: () => import('../../tools/file-base64/file-base64').then((m) => m.FileBase64),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'jwt-verify',
    title: 'JWT Signature Verifier',
    shortTitle: 'JWT Verify',
    description: 'Verify a JWT signature locally against a shared secret or public key, or a fetched JWKS — with named presets for Auth0, Okta, Azure AD, and Google.',
    category: 'security',
    keywords: ['jwt', 'verify', 'signature', 'jwk', 'jwks', 'hmac', 'rsa', 'ecdsa', 'ps256', 'auth', 'token', 'oidc', 'auth0', 'okta', 'azure ad', 'entra', 'google'],
    route: '/tools/jwt-verify',
    load: () => import('../../tools/jwt-verify/jwt-verify').then((m) => m.JwtVerify),
    status: 'experimental',
    persistence: { input: 'none', preferences: 'local' },
    network: { required: true },
  },
  {
    id: 'jwt-signer',
    title: 'JWT Signer',
    shortTitle: 'JWT Signer',
    description: 'Sign a JWT with an HMAC secret or an RSA/EC/RSA-PSS private key, with in-browser key-pair generation.',
    category: 'security',
    keywords: ['jwt', 'sign', 'signature', 'hmac', 'rsa', 'ecdsa', 'ps256', 'key pair', 'auth', 'token'],
    route: '/tools/jwt-signer',
    load: () => import('../../tools/jwt-signer/jwt-signer').then((m) => m.JwtSigner),
    status: 'experimental',
    persistence: { input: 'none', preferences: 'local' },
  },
  {
    id: 'json-schema-validator',
    title: 'JSON Schema Validator',
    shortTitle: 'Schema Validator',
    description: 'Validate a JSON instance against a Draft-07 or 2020-12 JSON Schema, with per-error paths.',
    category: 'data',
    keywords: ['json schema', 'validate', 'draft-07', '2020-12', 'ajv', 'schema', 'instance', 'validation'],
    route: '/tools/json-schema-validator',
    load: () => import('../../tools/json-schema-validator/json-schema-validator').then((m) => m.JsonSchemaValidator),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'advanced-diff',
    title: 'Advanced Diff / Merge',
    shortTitle: 'Advanced Diff',
    description: 'Line, word, and character diffing with a side-by-side two-way or three-way merge view, file upload, and unified-diff export.',
    category: 'text',
    keywords: ['diff', 'merge', 'patch', 'unified diff', 'compare', 'word diff', 'character diff', 'hunks', 'three-way merge', 'base', 'common ancestor'],
    route: '/tools/advanced-diff',
    load: () => import('../../tools/advanced-diff/advanced-diff').then((m) => m.AdvancedDiff),
    status: 'experimental',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'rich-text-editor',
    title: 'Rich Text Editor',
    shortTitle: 'Rich Text',
    description: 'WYSIWYG editor with sanitized HTML and Markdown export.',
    category: 'documents',
    keywords: ['wysiwyg', 'rich text', 'editor', 'html', 'markdown', 'tiptap', 'formatting', 'word processor'],
    route: '/tools/rich-text-editor',
    load: () => import('../../tools/rich-text-editor/rich-text-editor').then((m) => m.RichTextEditor),
    status: 'experimental',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'none' },
  },
  {
    id: 'markdown-workspace',
    title: 'Advanced Markdown Workspace',
    shortTitle: 'Markdown Workspace',
    description: 'Markdown editor with GFM tables/task lists, front matter, table of contents, and synced preview.',
    category: 'documents',
    keywords: ['markdown', 'gfm', 'front matter', 'yaml', 'toc', 'table of contents', 'word count', 'tables', 'task list'],
    route: '/tools/markdown-workspace',
    load: () => import('../../tools/markdown-workspace/markdown-workspace').then((m) => m.MarkdownWorkspace),
    status: 'experimental',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
];
