import { ToolDefinition } from '../../shared/models/tool-definition.model';

export const TOOL_DEFINITIONS: readonly ToolDefinition[] = [
  {
    id: 'text-inspector',
    title: 'Text Inspector',
    description: 'Character, word, line, and byte metrics for any text.',
    category: 'text',
    keywords: ['text', 'inspector', 'count', 'characters', 'words', 'lines', 'bytes', 'metrics'],
    route: '/tools/text-inspector',
    load: () => import('../../tools/text-inspector/text-inspector').then((m) => m.TextInspector),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'base64',
    title: 'Base64 Encoder / Decoder',
    description: 'UTF-8-safe text-to-Base64 and Base64-to-text conversion.',
    category: 'encoding',
    keywords: ['base64', 'encode', 'decode', 'encoding', 'utf-8'],
    route: '/tools/base64',
    load: () => import('../../tools/base64/base64').then((m) => m.Base64Tool),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'unix-timestamp',
    title: 'Unix Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates.',
    category: 'date-time',
    keywords: ['unix', 'timestamp', 'epoch', 'date', 'time', 'utc', 'convert'],
    route: '/tools/unix-timestamp',
    load: () => import('../../tools/unix-timestamp/unix-timestamp').then((m) => m.UnixTimestamp),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'jwt',
    title: 'JWT Debugger',
    description: 'Decode a JWT header and payload — does not verify signatures.',
    category: 'security',
    keywords: ['jwt', 'json web token', 'decode', 'auth', 'token', 'claims'],
    route: '/tools/jwt',
    load: () => import('../../tools/jwt/jwt').then((m) => m.Jwt),
    status: 'stable',
    persistence: { input: 'none', preferences: 'none' },
  },
  {
    id: 'hash',
    title: 'Hash Generator',
    description: 'MD5, SHA-1, SHA-256, SHA-384, and SHA-512 digests for text.',
    category: 'security',
    keywords: ['hash', 'checksum', 'md5', 'sha1', 'sha256', 'sha512', 'digest'],
    route: '/tools/hash',
    load: () => import('../../tools/hash/hash').then((m) => m.Hash),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'markdown',
    title: 'Markdown Preview',
    description: 'Live side-by-side Markdown editor and sanitized HTML preview.',
    category: 'documents',
    keywords: ['markdown', 'md', 'preview', 'render', 'documents'],
    route: '/tools/markdown',
    load: () => import('../../tools/markdown/markdown').then((m) => m.Markdown),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'regex',
    title: 'Regex Tester',
    description: 'Test a regular expression against text with match and capture-group details.',
    category: 'developer',
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test', 'capture groups'],
    route: '/tools/regex',
    load: () => import('../../tools/regex/regex').then((m) => m.Regex),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'diff',
    title: 'Text Diff',
    description: 'Line-oriented diff between two blocks of text.',
    category: 'text',
    keywords: ['diff', 'compare', 'text', 'changes', 'delta'],
    route: '/tools/diff',
    load: () => import('../../tools/diff/diff').then((m) => m.Diff),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'required' },
  },
  {
    id: 'json',
    title: 'JSON Formatter',
    description: 'Validate, format, and minify JSON.',
    category: 'data',
    keywords: ['json', 'format', 'validate', 'pretty', 'minify'],
    route: '/tools/json',
    load: () => import('../../tools/json/json').then((m) => m.Json),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'uuid',
    title: 'UUID Generator / Inspector',
    description: 'Generate RFC 4122 v4 UUIDs and inspect an existing UUID’s version and variant.',
    category: 'developer',
    keywords: ['uuid', 'guid', 'generate', 'inspect', 'identifier', 'rfc 4122'],
    route: '/tools/uuid',
    load: () => import('../../tools/uuid/uuid').then((m) => m.Uuid),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'url-encode',
    title: 'URL Encoder / Decoder',
    description: 'Percent-encode or decode text as a URL component or a full URI.',
    category: 'encoding',
    keywords: ['url', 'uri', 'encode', 'decode', 'percent-encoding', 'escape', 'unescape'],
    route: '/tools/url-encode',
    load: () => import('../../tools/url-encode/url-encode').then((m) => m.UrlEncode),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'query-string',
    title: 'Query String Parser / Builder',
    description: 'Parse a query string or URL into key/value pairs, or build one from scratch.',
    category: 'web',
    keywords: ['query string', 'query params', 'url', 'parse', 'build', 'search params'],
    route: '/tools/query-string',
    load: () => import('../../tools/query-string/query-string').then((m) => m.QueryString),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'case-converter',
    title: 'Case Converter',
    description: 'Convert text between camelCase, snake_case, kebab-case, Title Case, and more.',
    category: 'text',
    keywords: ['case', 'convert', 'camelcase', 'snake_case', 'kebab-case', 'title case', 'pascalcase'],
    route: '/tools/case-converter',
    load: () => import('../../tools/case-converter/case-converter').then((m) => m.CaseConverter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'whitespace-cleaner',
    title: 'Whitespace Cleaner / Normalizer',
    description: 'Trim, collapse, and normalize whitespace, line endings, and invisible characters.',
    category: 'text',
    keywords: ['whitespace', 'trim', 'clean', 'normalize', 'line endings', 'tabs', 'spaces', 'invisible'],
    route: '/tools/whitespace-cleaner',
    load: () => import('../../tools/whitespace-cleaner/whitespace-cleaner').then((m) => m.WhitespaceCleaner),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'slug-generator',
    title: 'Slug Generator',
    description: 'Turn a title into a URL-friendly slug, with transliteration and length control.',
    category: 'text',
    keywords: ['slug', 'url', 'permalink', 'seo', 'transliterate', 'hyphenate'],
    route: '/tools/slug-generator',
    load: () => import('../../tools/slug-generator/slug-generator').then((m) => m.SlugGenerator),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'html-entities',
    title: 'HTML Entity Encoder / Decoder',
    description: 'Encode text as HTML entities, or decode named and numeric entities back to text.',
    category: 'encoding',
    keywords: ['html', 'entity', 'entities', 'encode', 'decode', 'escape', 'unescape', 'amp', 'nbsp'],
    route: '/tools/html-entities',
    load: () => import('../../tools/html-entities/html-entities').then((m) => m.HtmlEntities),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'color-converter',
    title: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL, HSV, CMYK, and named CSS colors.',
    category: 'encoding',
    keywords: ['color', 'colour', 'hex', 'rgb', 'hsl', 'hsv', 'cmyk', 'convert', 'css color'],
    route: '/tools/color-converter',
    load: () => import('../../tools/color-converter/color-converter').then((m) => m.ColorConverter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
  {
    id: 'number-base',
    title: 'Number Base Converter',
    description: 'Convert whole numbers between binary, octal, decimal, hex, or any base 2–36.',
    category: 'encoding',
    keywords: ['number', 'base', 'binary', 'octal', 'decimal', 'hex', 'hexadecimal', 'radix', 'convert'],
    route: '/tools/number-base',
    load: () => import('../../tools/number-base/number-base').then((m) => m.NumberBase),
    status: 'stable',
    persistence: { input: 'local', preferences: 'none' },
  },
  {
    id: 'yaml-json',
    title: 'YAML ↔ JSON Converter',
    description: 'Convert between YAML and JSON, in either direction.',
    category: 'data',
    keywords: ['yaml', 'json', 'convert', 'yml', 'data'],
    route: '/tools/yaml-json',
    load: () => import('../../tools/yaml-json/yaml-json').then((m) => m.YamlJson),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'xml-formatter',
    title: 'XML Formatter',
    description: 'Validate, format, and minify XML.',
    category: 'data',
    keywords: ['xml', 'format', 'validate', 'pretty', 'minify'],
    route: '/tools/xml-formatter',
    load: () => import('../../tools/xml-formatter/xml-formatter').then((m) => m.XmlFormatter),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'csv-viewer',
    title: 'CSV Viewer / Converter',
    description: 'View CSV as a table, and convert between CSV and JSON.',
    category: 'data',
    keywords: ['csv', 'table', 'convert', 'json', 'tsv', 'spreadsheet'],
    route: '/tools/csv-viewer',
    load: () => import('../../tools/csv-viewer/csv-viewer').then((m) => m.CsvViewer),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'json-query',
    title: 'JSONPath / JMESPath Tester',
    description: 'Query JSON with a JSONPath or JMESPath expression.',
    category: 'data',
    keywords: ['jsonpath', 'jmespath', 'query', 'json', 'filter', 'search'],
    route: '/tools/json-query',
    load: () => import('../../tools/json-query/json-query').then((m) => m.JsonQuery),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
    execution: { worker: 'optional' },
  },
  {
    id: 'http-status',
    title: 'HTTP Status Code Reference',
    description: 'Searchable reference of every IANA-registered HTTP status code.',
    category: 'web',
    keywords: ['http', 'status', 'code', 'response', 'reference', '404', '500'],
    route: '/tools/http-status',
    load: () => import('../../tools/http-status/http-status').then((m) => m.HttpStatus),
    status: 'stable',
    persistence: { input: 'local', preferences: 'none' },
  },
  {
    id: 'http-header-inspector',
    title: 'HTTP Header Inspector / Builder',
    description: 'Inspect pasted HTTP headers as key/value pairs, or build a header set from scratch.',
    category: 'web',
    keywords: ['http', 'header', 'headers', 'inspect', 'build', 'request', 'response'],
    route: '/tools/http-header-inspector',
    load: () =>
      import('../../tools/http-header-inspector/http-header-inspector').then((m) => m.HttpHeaderInspector),
    status: 'stable',
    persistence: { input: 'none', preferences: 'none' },
  },
  {
    id: 'curl-converter',
    title: 'cURL Command Inspector / Converter',
    description: 'Parse a cURL command into its parts, build one interactively, and export it as code.',
    category: 'web',
    keywords: ['curl', 'http', 'request', 'convert', 'fetch', 'code export'],
    route: '/tools/curl-converter',
    load: () => import('../../tools/curl-converter/curl-converter').then((m) => m.CurlConverter),
    status: 'stable',
    persistence: { input: 'none', preferences: 'local' },
  },
  {
    id: 'cron',
    title: 'Cron Expression Parser',
    shortTitle: 'Cron Parser',
    description: 'Parse a cron expression into a human-readable schedule and preview its next run times.',
    category: 'date-time',
    keywords: ['cron', 'crontab', 'schedule', 'next run', 'expression'],
    route: '/tools/cron',
    load: () => import('../../tools/cron/cron').then((m) => m.Cron),
    status: 'stable',
    persistence: { input: 'session', preferences: 'local' },
  },
  {
    id: 'user-agent',
    title: 'User-Agent Parser',
    description: 'Break a User-Agent string down into browser, engine, OS, and device details.',
    category: 'web',
    keywords: ['user agent', 'ua', 'browser', 'device', 'os', 'parse'],
    route: '/tools/user-agent',
    load: () => import('../../tools/user-agent/user-agent').then((m) => m.UserAgent),
    status: 'stable',
    persistence: { input: 'session', preferences: 'none' },
  },
];
